package com.drwtrading.london.reddal;

public enum OPXLComponents {

    SELECT_IO,

    OPXL_ULTIMATE_PARENT,
    OPXL_FX_CALC,
    OPXL_ETF_STACK_MANAGER_FILTERS,
    OPXL_SPREAD_STACK_MANAGER_FILTERS,
    OPXL_SPREAD_PREMIUM_WRITER,
    OPXL_ISINS_GOING_EX,
    OPXL_LADDER_TEXT,
    OPXL_POSITION_SUBSCRIBER,
    OPXL_OBLIGATIONS_RFQ,
    OPXL_BEST_WORKING_ORDER_WRITER,
}
